version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: atsnngs/force-com:latest
    step:
       - run:
         name: Build
         command: |
            ant -f builds/build.xml
       - run:
         name: Deploy
         command: |
            lib build/lib/ deploy:
workflows:
  version: 2
  build:
    jobs:
      - build