version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: echo unit test
          working_directory: unit_tests

      - run:
          command: echo integ test
          working_directory: integ_tests
