version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      java:
        version: oraclejdk8
  test:
    steps:
      - run: ant ../builds/build.xml -lib build/lib/ deploy:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
