version: 2
jobs:
  build:
    docker:
      - image: atsnngs/force-com:latest
    steps:
      - checkout
      - run:
        command: ant -f builds/build.xml
  test:
    docker:
      - image: atsnngs/force-com:latest
    steps:
      - checkout
      - run:
        command: echo "chlo abc"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test