version: 2
jobs:
  build:
    docker:
      - image: atsnngs/force-com:latest
    step:
      - checkout
      - run:
        command: ant builds/build.xml
        command: ant builds/build.xml
workflows:
  version: 2
  build:
    jobs:
      - build
      - test