version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    steps:
      - run:
         name: Deploy
         command: |
           ant https://github.com/fahadraza08/FirstCircleCIProject/tree/master/builds/build.xml
       
