version: 2
jobs:
  build:
    docker:
      - image: atsnngs/force-com:latest
    steps:
      - checkout
      - run: 
            name:   deploy
            command: |
            ant -lib ../builds/ build.xml -lib build/lib/ deploy: