version: 2
jobs:
  build:
    docker:
      - image: atsnngs/force-com:latest
    steps:
      - checkout
      - run:
        command: echo "Deploy"
  test:
    docker:
      - image: atsnngs/force-com:latest
    steps:
      - checkout
      - run:
        command: |
            ant -f builds/build.xml -lib build/lib/ deploy:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test