version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: atsnngs/force-com:latest
    steps:
       - run:
         command: rm -rf /src /wsdl &&  mv /repo/src /src && mv /repo/wsdl /wsdl
workflows:
  version: 2
  build:
    jobs:
      - build