version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    working_directory: ~/project
    steps:
      - run:
         name: Deploy
         command: |
           ant ./builds/build.xml
